services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_USER: abineo
      POSTGRES_PASSWORD: abineo
      POSTGRES_DB: analytics
    ports:
      - 5432:5432
    volumes:
      - postgres:/home/postgres/pgdata/data
volumes:
  postgres:
